### PR TITLE
Once failed to save a new resource, the resource cannot be saved again

### LINKED ISSUE #167: Once failed to save a new resource, the resource cannot be saved again correctly
1. In Fusion, open "Asset Manager", click "New Imagery Resource", add some invalid file(s) (e.g. unsupported file, or Tiff file without SRS, or no file at all) to the "Source File(s)" list.
2. Select File menu -> Save. Specify a resource name, then click "Save".

After an error message shows up as expected, there are problems:

- "Save" in File menu is disabled.
- "Save As..." looks OK, but any attempt to correct the "Source File(s)" list would be futile. The resource cannot be saved because the same error is raised again.

To proceed, I have to close the window and open a new one.

(Built on Ubuntu 14)

### PR DESCRIPTION
**Pull request by tst-awankhede**
resolves #167

### CODE REVIEW

**Comment by tst-eclamar** [comment]
I was able to reproduce the error.

However, the code fix does not solve the problem; or, more specifically,  changes the problem.  Now, after selecting 'Save', and getting an error about no resource selected, one can select 'Save' again (note at this point: the 'Build' option is not grayed out either) and it will 'work'.  The 'Save' button is now grayed out, but there is no image specified.

**Comment by tst-awankhede** [comment]
That is happening because the Sources list has not checked in IsModified, hence even if we take out the sources, they don't generate any save error.

However, that was not the case before. Before , any error would block the path of correction and save again so this path was not even tested.

I am looking to implement it, in general enabling the "save->fail->save " as part of same request has many variations to test and go bad.

**Comment by tst-eclamar** [comment]
I'm not sure that I understand your comments.  Do you plan on dealing with the bugs that were exposed by your change in different ticket?  Or are you continuing under the current ticket?

**Comment by tst-awankhede** [comment]
I will try today and update if possible in next couple hours.

**Comment by tst-awankhede** [comment]
I could not come up with a reasonable solution for these existing bugs which would eventually address your observations refer #321.  ( other issues in this part of code are #309 #316 )

**Comment by tst-awankhede** [comment]
updated code it now solves #309 and also checks that there should be at least one src file.

**Comment by tst-lsavoie** [comment]
Just to be clear, this fixes the problem where you try to save with no files and then add a file and save again.  It doesn't fix the problem where you try to save with an invalid file, then change the file and try again.  Do I have that right?  I think we can merge these changes but we're going to need to leave #167 open to make sure we handle the other cases.

**Comment by tst-awankhede** [comment]
yes, fixes #309 and part of #167 , so we can keep the #167 open as discussed.

**Comment by tst-eclamar** [comment]
@tst-lsavoie I haven't looked at it recently - I really should look at it
again, just to be sure.  However, I leave it up to you.

**Comment by tst-lsavoie** [comment]
@tst-eclamar if you have time to look at it tomorrow, go ahead and do that.  Otherwise we'll just merge it in tomorrow.

**Comment by tst-eclamar** [comment]
@tst-lsavoie I've tested it out and it seems good.  Thanks.

File: earth_enterprise/src/fusion/fusionui/RasterAssetWidget.cpp [hunk 1]
```diff
@@ -655,7 +659,7 @@ void RasterAssetWidget::AssembleEditRequest(
                           + filename + "\n" +
                           khErrnoException::errorString(errno));
       case SourceConfig::NonVolume:
-        throw khException(filename + tr(" doesn't reside on a known volume."));
+        throw khException(filename + tr(" doesn't reside on a known volume. \n Make sure the volume is configured correctly using geconfigureassetroot and try again."));
```
Comment (tst-ppenev) [inline earth_enterprise/src/fusion/fusionui/RasterAssetWidget.cpp]: I think most users want to move their files to a 'known volume', rather than create a new one.

Comment (tst-lsavoie) [inline earth_enterprise/src/fusion/fusionui/RasterAssetWidget.cpp]: @tst-ppenev would you like this change made?  Other than this, the PR is ready to merge.

Comment (tst-awankhede) [inline earth_enterprise/src/fusion/fusionui/RasterAssetWidget.cpp]: @tst-ppenev : Hint to use geconfigureassetroot is on purpose, it should help determine the volume ( using --listvolume) and edit or add volume if needed. Move option( as you proposed) is pretty much specific action resolution that might not work for all errors.

If this does not seem reasonable, please propose one the error message.

Comment (tst-ppenev) [inline earth_enterprise/src/fusion/fusionui/RasterAssetWidget.cpp]: Something like:

> You can move your asset files to a known volume, or create a new one that contains their current location.  You can list known volumes and create new ones from the command line with `geconfigureassetroot`.

Comment (tst-ppenev) [inline earth_enterprise/src/fusion/fusionui/RasterAssetWidget.cpp]: @tst-lsavoie: It seems like a quick change. Otherwise, if it is taking up more time, I don't think it's important enough to hold the ticket.

Comment (tst-awankhede) [inline earth_enterprise/src/fusion/fusionui/RasterAssetWidget.cpp]: sure, I will send the change

**Comment by tst-awankhede** [comment]
New error message:     screenshot from 2017-07-14 15-07-51

**Comment by tst-ppenev** [comment]
@tst-awankhede: Lol. I hope that dialog box does word wrapping.

**Comment by tst-awankhede** [comment]
No word wrapping there. Haha

**Comment by tst-ppenev** [comment]
Maybe a newline between the two sentences can help, then. The rule of thumb in typography is 66 characters per line. This looks 'a little' above that.

**Comment by tst-awankhede** [comment]
screenshot from 2017-07-17 14-16-05

changes as per screenshot above
