### PR TITLE
Fixes #646: rpm scripting fixes to correctly support package upgrading

### LINKED ISSUE #646: RPMs fail to upgrade with future releases
Build and install a set of opengee rpm's, called 5.2.x-1.

Manually modify the build.gradle file, change line release = "1.$

{rpmPlatformString}" to release = "2.${rpmPlatformString}".

Build a new set of opengee rpms, which will have 5.2.x-2 as their version number.

Use yum install or rpm -Uhv to try and update your previously installed 5.2.x-1 packages to this new 5.2.x-2 version.

Expected Result:

Upgrade completes without errors, you now are using 5.2.x-2.

Actual Result:

opengee-common will fail in pre-uninstall, and block updating from completing. System state may even become bad.

### PR DESCRIPTION
**Pull request by tst-dsugar**
Fixes #646

### CODE REVIEW

**Comment by tst-dsugar** [comment]
@tst-ccamp this is what I came up with...

File: earth_enterprise/rpms/opengee-common/post-uninstall.sh [hunk 1]
```diff
@@ -22,18 +22,23 @@ BININSTALLROOTDIR="/etc/init.d"
 
 #------------------------------------------------------------------------------
 # Group names:
-GEGROUP_NAME=$(cat "$BININSTALLROOTDIR/gevars.sh" | grep GEGROUP | cut  -d'=' -f2)
-
 
 remove_users_groups()
```
Comment (tst-ppenev) [inline earth_enterprise/rpms/opengee-common/post-uninstall.sh]: Suggestion: Consider replacing this script with just printing a message that the system administrator may want to remove `gegroup`, if there are now files or directories using it.

File: earth_enterprise/rpms/opengee-common/pre-install.sh [hunk 2]
```diff
@@ -24,9 +24,6 @@ check_group()
     # Add group if it does not exist:
     if [ -z "$GROUP_EXISTS" ]; then
```
Comment (tst-ppenev) [inline earth_enterprise/rpms/opengee-common/pre-install.sh]: Suggestion: You can replace this function with `groupadd -f -r "$GEGROUP"`.

File: earth_enterprise/rpms/opengee-fusion/post-uninstall.sh [hunk 3]
```diff
@@ -26,4 +26,7 @@ remove_users_and_groups()
 # Main Function
 #-----------------------------------------------------------------
 
-remove_users_and_groups
+# remove users only if actually uninstalling
+if [ "$1" = "0" ] ; then
+    remove_users_and_groups
```
Comment (tst-ppenev) [inline earth_enterprise/rpms/opengee-fusion/post-uninstall.sh]: Suggestion: We may want to just print a message that the system administrator can delete `gefusionuser`, if no files or directories are using it.

File: earth_enterprise/rpms/opengee-fusion/pre-install.sh [hunk 4]
```diff
@@ -70,11 +81,11 @@ create_users_and_groups()
 		mkdir -p "$BASEINSTALLDIR_OPT/.users/$GEFUSIONUSER"
 		useradd --home "$BASEINSTALLDIR_OPT/.users/$GEFUSIONUSER" \
             --system --gid "$GEGROUP" "$GEFUSIONUSER"
-        keyvalue_file_set "$GEE_INSTALL_KV_PATH" gefusionuser_existed "false"
 	else
```
Comment (tst-ppenev) [inline earth_enterprise/rpms/opengee-fusion/pre-install.sh]: Lint: Fix indentation.

File: earth_enterprise/rpms/opengee-fusion/post-install.sh [hunk 5]
```diff
@@ -148,11 +157,7 @@ install_or_upgrade_asset_root()
     else
         # upgrade asset root -- if this is a master
         if [ "$IS_SLAVE" = false ]; then
-            # TODO: Verify this logic -- this is what is defined in the
-            # installer documentation, but needs confirmation
-            keyvalue_file_get "$GEE_INSTALL_KV_PATH" gegroup_existed NEW_GEFUSIONUSER
-            keyvalue_file_get "$GEE_INSTALL_KV_PATH" gefusionuser_existed NEW_GEFUSIONUSER
-            if [ "$NEW_GEGROUP" = true ] || [ "$NEW_GEFUSIONUSER" = true ]; then
+            if [ "$NEW_INSTALL" = false ] ; then
```
Comment (tst-ppenev) [inline earth_enterprise/rpms/opengee-fusion/post-install.sh]: Q: How does this test if installing the `opengee-common` package created a new `gegroup` or not?

Q: Can we test whether to 'upgrade' by checking if one of the top-level directories has the wrong permissions?  Do we know upgrading from what version of GEE to what version of GEE requires changing file ownership?

File: earth_enterprise/rpms/opengee-server/post-install.sh [hunk 6]
```diff
@@ -17,6 +17,12 @@
 set +x
 umask 002
 
+# we are not using this yet, but is probably good to have if we need to
```
Comment (tst-ppenev) [inline earth_enterprise/rpms/opengee-server/post-install.sh]: Minor: I don't think we should have code that's not used anywhere.  We can add it when we need it.

Comment (tst-dsugar) [reply earth_enterprise/rpms/opengee-server/post-install.sh]: I have killed all the post-install scripts in gradle now, because they only were involved in removing users and groups.  I could nuke the files as well...

File: earth_enterprise/rpms/opengee-fusion/post-uninstall.sh (hunk 3 above)
Comment (tst-dsugar) [reply earth_enterprise/rpms/opengee-fusion/post-uninstall.sh]: We could.  For now I killed the post-uninstalls entirely in gradle...

File: earth_enterprise/rpms/opengee-server/post-install.sh (hunk 6 above)
Comment (tst-ppenev) [reply earth_enterprise/rpms/opengee-server/post-install.sh]: I think it's useful to print a message reminding a system administrator that they can remove the users and groups, if they want to.

File: earth_enterprise/rpms/opengee-common/post-uninstall.sh [hunk 7]
```diff
@@ -22,18 +22,23 @@ BININSTALLROOTDIR="/etc/init.d"
...
 {
-    if [ -n "$(getent group "$GEGROUP_NAME")" ]; then
-        groupdel "$GEGROUP_NAME"
+    local GROUP_EXISTS=$(getent group "$GEGROUP")
+
+    # Add group if it does not exist:
```
Comment (tst-ppenev) [inline earth_enterprise/rpms/opengee-common/post-uninstall.sh]: Minor: I don't think the command below is adding a group.

Comment (tst-dsugar) [reply earth_enterprise/rpms/opengee-common/post-uninstall.sh]: Yes, I was trying to make add and delete consistent (they were originally very differently coded), and that is a copy-paste error.  But it may not matter since the post-uninstall is no longer in gradle.

File: earth_enterprise/rpms/opengee-server/post-install.sh (hunk 6 above)
Comment (tst-dsugar) [reply earth_enterprise/rpms/opengee-server/post-install.sh]: You have a good point.  I can re-activate the post-uninstalls and use it for that.

File: earth_enterprise/rpms/opengee-common/pre-install.sh [hunk 8]
```diff
@@ -24,9 +24,6 @@ check_group()
...
         groupadd -r "$GEGROUP" &> /dev/null
-        keyvalue_file_set "$GEE_INSTALL_KV_PATH" gegroup_existed "false"
```
Comment (tst-ppenev) [inline earth_enterprise/rpms/opengee-common/pre-install.sh]: Old comment: This used to part of determining whether to change ownership and 'upgrade' a Fusion asset root. Now it seems to be simply omitted.  Are we sure that a user can't bring in an old asset root with the wrong group?

File: earth_enterprise/rpms/opengee-fusion/post-install.sh [hunk 9]
```diff
@@ -183,7 +189,7 @@ END
 
 final_assetroot_configuration()
 {
-    if [ "$IS_SLAVE" = true ]; then
+    if [ "$IS_SLAVE" == "true" ]; then
```
Comment (tst-ppenev) [inline earth_enterprise/rpms/opengee-fusion/post-install.sh]: Lint: `==` is not a POSX operator, '=' is.  In case we care about POSIX compliance.

File: earth_enterprise/rpms/opengee-common/pre-install.sh (hunk 2 above)
Comment (tst-dsugar) [reply earth_enterprise/rpms/opengee-common/pre-install.sh]: is it valid for both rhel6 and 7?

File: earth_enterprise/rpms/opengee-fusion/post-install.sh (hunk 5 above)
Comment (tst-dsugar) [reply earth_enterprise/rpms/opengee-fusion/post-install.sh]: We now know that opengee-common creates in it's pre-install now, and does not remove it all (or only in a post-uninstall when not upgrading), so we assume it's there based on this.  There are other/other kinds of tests we could do, but I was trying to keep consistent with practices common to other packages.

Comment (tst-dsugar) [reply earth_enterprise/rpms/opengee-fusion/post-install.sh]: There are things we also probably still over do, and could do more checks for, but I did not want to invalidate all prior testing, and so focused on the issues around package updating itself only rather than about some of the extra and misc warning messages we still do get.

File: earth_enterprise/rpms/opengee-common/pre-install.sh (hunk 2 above)
Comment (tst-ppenev) [reply earth_enterprise/rpms/opengee-common/pre-install.sh]: Yes.

File: earth_enterprise/rpms/opengee-common/pre-install.sh (hunk 8 above)
Comment (tst-dsugar) [reply earth_enterprise/rpms/opengee-common/pre-install.sh]: There is a different way that this is checked for now, and the post-install.sh treats the rpm fresh install as an "upgrade" install for this if there was a prior non-rpm install found.  This should produce the same behavior as before, because gegroup_existed detection was actually used indirectly to determine install/upgrade behavior in post-install.sh prior.

File: earth_enterprise/rpms/opengee-fusion/post-install.sh [hunk 10]
```diff
@@ -147,12 +157,8 @@ install_or_upgrade_asset_root()
...
     else
         # upgrade asset root -- if this is a master
-        if [ "$IS_SLAVE" = false ]; then
-            # TODO: Verify this logic -- this is what is defined in the
-            # installer documentation, but needs confirmation
-            keyvalue_file_get "$GEE_INSTALL_KV_PATH" gegroup_existed NEW_GEFUSIONUSER
-            keyvalue_file_get "$GEE_INSTALL_KV_PATH" gefusionuser_existed NEW_GEFUSIONUSER
-            if [ "$NEW_GEGROUP" = true ] || [ "$NEW_GEFUSIONUSER" = true ]; then
+        if [ "$IS_SLAVE" = "false" ]; then
+            if [ "$NEW_INSTALL" = "false" ] ; then
```
Comment (tst-ppenev) [inline earth_enterprise/rpms/opengee-fusion/post-install.sh]: What I'm saying is that this is modifying the existing behavior by no longer testing if `gegroup` was created.

I don't think the question is whether `gegroup` exists after it is created by installing `opengee-common`.  What I understand the code is trying to do is:

* If asset data existed before `gegroup` or `gefusionuser` were created in the install scripts, change file ownership of the data.
* If `gegroup` and `gefusionuser` already existed before starting an installation, assume ownership is correct, and don't change it.

This change skips the test for whether `gegroup` existed.  I think we could write the tests better, but I'm wondering if it's a good idea to skip one of them.

Comment (tst-dsugar) [reply earth_enterprise/rpms/opengee-fusion/post-install.sh]: And what I am saying is I deduce this from rather different means, based on both the rpm install/upgrade state, and also on how NEW_INSTALL gets set if there was a prior non-rpm install.

Comment (tst-ppenev) [reply earth_enterprise/rpms/opengee-fusion/post-install.sh]: The test for 'a prior non-rpm install' seems to be whether `/etc/init.d/gefusion` exists.  So, if a user had an old version of GEE and Fusion with some data, uninstalled them, and installed RPMs, that assert root owner update will no longer happen, and Fusion would complain.  (I don't think it would work to install RPMs while the old version is installed anyway, at least until we implement the upgrade scripts from old versions.)

This is not very hard to fix, so I don't think it's a great problem, but we also don't have to introduce it.

Comment (tst-dsugar) [reply earth_enterprise/rpms/opengee-fusion/post-install.sh]: I believe we already had this problem possible in the older script.

Comment (tst-ppenev) [reply earth_enterprise/rpms/opengee-fusion/post-install.sh]: :stuck_out_tongue: The older script wouldn't have that problem, since it relied on whether the group and user existed, not on whether `/etc/init.d/gefusion` existed. Anyway, we can tell an administrator how to fix that after an upgrade.

**Comment by tst-dsugar** [comment]
@tst-nfarah https://github.com/google/earthenterprise/issues/646 describes the issue and steps to reproduce that is pr will resolve.  I should have added the ticket earlier.

File: earth_enterprise/rpms/opengee-fusion/post-install.sh (hunk 10 above)
Comment (tst-ppenev) [reply earth_enterprise/rpms/opengee-fusion/post-install.sh]: Could you add a small Markdown file on upgrading that includes the command to update an asset root from an old install?

**Comment by tst-ppenev** [comment]
Q: Why does this pull request seem to include a lot of unrelated changes from other pull requests, like adding `rpmrebuild` and `GitPython` to build environment scripts, and adding RPM and Deb build classes?

**Comment by tst-ccamp** [comment]
@tst-dsugar I think merging master into your feature branch will fix those weird problems with unrelated commits

**Comment by tst-dsugar** [comment]
It should be clean now

File: earth_enterprise/rpms/opengee-common/post-uninstall.sh [hunk 11]
```diff
@@ -22,18 +22,18 @@ BININSTALLROOTDIR="/etc/init.d"
...
 # Group names:
-GEGROUP_NAME=$(cat "$BININSTALLROOTDIR/gevars.sh" | grep GEGROUP | cut  -d'=' -f2)
-
 
 remove_users_groups()
 {
-    if [ -n "$(getent group "$GEGROUP_NAME")" ]; then
-        groupdel "$GEGROUP_NAME"
-    fi
+    echo "opengee group $GEGROUP may now be safely removed."
```
Comment (tst-ppenev) [inline earth_enterprise/rpms/opengee-common/post-uninstall.sh]: Style: 'opengee' -> 'OpenGEE'

Minor: The group can be safely removed, only if the system administrator can confirm there are no more files or directories owned by it.

File: earth_enterprise/rpms/opengee-fusion/post-uninstall.sh [hunk 12]
```diff
@@ -16,14 +16,15 @@
 
 remove_users_and_groups()
 {
-    if getent passwd "$GEFUSIONUSER" > /dev/null; then
-        userdel "$GEFUSIONUSER"
-    fi
+    echo "opengee user $GEFUSIONUSER may now be safely removed."
```
Comment (tst-ppenev) [inline earth_enterprise/rpms/opengee-fusion/post-uninstall.sh]: Style: 'opengee' -> 'OpenGEE'

Minor: The user can be removed safely only if the system administrator can confirm there are no files owned by that user that can appear on the machine.

File: earth_enterprise/rpms/opengee-fusion/pre-install.sh [hunk 13]
```diff
@@ -15,13 +15,27 @@
...
 #-----------------------------------------------------------------
 # Main Functions
 #-----------------------------------------------------------------
 main_preinstall()
 {
+    # cleanup of special non-rpm upgrade case flag...
+    rm -f "$BASEINSTALLDIR_OPT/.upgrade-migration"
+
+    # Whether rpm or non-rpm upgrade...
     if [ -f /etc/init.d/gefusion ]; then
```
Comment (tst-ppenev) [inline earth_enterprise/rpms/opengee-fusion/pre-install.sh]: Q: How did you test this code?  Were you able to do a non-RPM upgrade with these RPMs?

File: earth_enterprise/rpms/opengee-server/post-uninstall.sh [hunk 14]
```diff
@@ -21,20 +21,14 @@ set +x
...
-    # Fedora recommends to never delete users that a package has created:
-    #   https://fedoraproject.org/wiki/Packaging:UsersAndGroups
-    # TODO: Consider whether we want to remove this:
-    if getent passwd "$GEAPACHEUSER" >/dev/null; then
-        userdel "$GEAPACHEUSER"
-    fi
-    if getent passwd "$GEPGUSER" >/dev/null; then
-        userdel "$GEPGUSER"
-    fi
+    echo "opengee users $GEAPACHEUSER and $GEPGUSER may now safely be removed."
```
Comment (tst-ppenev) [inline earth_enterprise/rpms/opengee-server/post-uninstall.sh]: Same comments as above.

Style: 'opengee' -> 'OpenGEE'

Minor: The message would be more accurate, if it said the users and groups can be removed, if there are no files or directories owned by them.

File: earth_enterprise/rpms/opengee-common/pre-install.sh (hunk 8 above)
Comment (tst-dsugar) [reply earth_enterprise/rpms/opengee-common/pre-install.sh]: So you are suggesting we add a chgrp -r gegroup /gevol if we are doing a non-rpm upgrade and there is an existing /gevol directory?  If so, that would be easy enough to add...

File: earth_enterprise/rpms/opengee-fusion/post-install.sh (hunk 10 above)
Comment (tst-dsugar) [reply earth_enterprise/rpms/opengee-fusion/post-install.sh]: If this is only a matter of permissions and assuring the group/ownership match up, it might be easier to do a chgrp/chown...

File: earth_enterprise/rpms/opengee-server/post-uninstall.sh (hunk 14 above)
Comment (tst-dsugar) [reply earth_enterprise/rpms/opengee-server/post-uninstall.sh]: true...let me do that now.

File: earth_enterprise/rpms/opengee-common/pre-install.sh (hunk 8 above)
Comment (tst-ppenev) [reply earth_enterprise/rpms/opengee-common/pre-install.sh]: I think that's what the code in `opengee-fusion/post-install.sh` does, e.g. when determining whether to pass the no-chown option to `geupgradeassetroot`.  The issue here is to determine when to do that ownership change.

File: earth_enterprise/rpms/opengee-fusion/pre-install.sh (hunk 13 above)
Comment (tst-dsugar) [reply earth_enterprise/rpms/opengee-fusion/pre-install.sh]: This is based on the idea that you install the rpms without first removing the non-rpm install (that is, you do not run uninstall-server.sh or uninstall-fusion.sh first).  If you think this is not a valid scenario, then I could remove the migration checking entirely and maybe that would be a better way to address the concern you are stating.

File: earth_enterprise/rpms/opengee-fusion/post-install.sh [hunk 15]
```diff
@@ -148,12 +158,8 @@ install_or_upgrade_asset_root()
...
                 NOCHOWN=""
                 UPGRADE_MESSAGE="The upgrade will fix permissions for the asset root and source volume. This may take a while."
```
Comment (tst-dsugar) [inline earth_enterprise/rpms/opengee-fusion/post-install.sh]: This talks about "upgrade", but not with the same meaning as rpm upgrade.  In the case of rpm's, we have nailed down the gegroup and users for the life of the rpm installs.  Hence, "upgrading", but from one rpm to a newer one, should I believe normally be done with --nochown, and the original NEW_INSTALL test a few lines about should actually be if true, as the full chown should be done if it is a new install and yet there is a prior asset root.  I think this misunderstanding is the real issue, and the upgrade-migration test then does actually become unnecessary.

File: earth_enterprise/rpms/opengee-common/pre-install.sh (hunk 8 above)
Comment (tst-dsugar) [reply earth_enterprise/rpms/opengee-common/pre-install.sh]: And now I do understand the concern completely, as being about when and why to set no-chown.

File: earth_enterprise/rpms/opengee-fusion/post-install.sh [hunk 16]
```diff
@@ -148,12 +152,9 @@ install_or_upgrade_asset_root()
...
     else
         # upgrade asset root -- if this is a master
-        if [ "$IS_SLAVE" = false ]; then
-            # TODO: Verify this logic -- this is what is defined in the
-            # installer documentation, but needs confirmation
-            keyvalue_file_get "$GEE_INSTALL_KV_PATH" gegroup_existed NEW_GEFUSIONUSER
-            keyvalue_file_get "$GEE_INSTALL_KV_PATH" gefusionuser_existed NEW_GEFUSIONUSER
-            if [ "$NEW_GEGROUP" = true ] || [ "$NEW_GEFUSIONUSER" = true ]; then
+        if [ "$IS_SLAVE" = "false" ]; then
+            OWNERSHIP=`find /gevol/assets -maxdepth 0 -printf "%g:%u"`
```
Comment (tst-dsugar) [inline earth_enterprise/rpms/opengee-fusion/post-install.sh]: @tst-ppenev so I came up with a new and more direct way to test asset file ownership. If ownership is same as rpm expects, it then sets nochown...

Comment (tst-ppenev) [reply earth_enterprise/rpms/opengee-fusion/post-install.sh]: Yeah, this is what I was suggesting earlier.  I have two comments:

* Use `"$ASSET_ROOT"` instead of hard coding `/gevol/assets`.
* I'm wondering if `-maxdepth 0` is going to be enough.  You could use something like `find -maxdepth 2 \( \! -user "$GEFUSIONUSER" \) -o \( \! -group "$GEGROUP" \)` to test whether you should `chown`.

**Comment by tst-dsugar** [comment]
I tested with -maxdepth 0 doing it this way...but yes, it should use "$ASSET_ROOT" to be most accurate.

File: earth_enterprise/rpms/opengee-server/pre-uninstall.sh [hunk 17]
```diff
@@ -17,16 +17,12 @@
...
-main_preuninstall()
-{
-    service geserver stop
-    remove_service geserver
-}
 
-#-----------------------------------------------------------------
-# Pre-install Main
-#-----------------------------------------------------------------
+service geserver stop
```
Comment (tst-ccamp) [inline earth_enterprise/rpms/opengee-server/pre-uninstall.sh]: You don't need to stop the service if this is an upgrade. You should only be doing things that don't effect a running service at this point. Or if you're supper worried about that, you can stop it, do your work, and then start it again.

File: earth_enterprise/rpms/opengee-fusion/pre-uninstall.sh [hunk 18]
```diff
@@ -21,6 +21,10 @@ set +x
 #-----------------------------------------------------------------
 
 service gefusion stop
```
Comment (tst-ccamp) [inline earth_enterprise/rpms/opengee-fusion/pre-uninstall.sh]: You don't need to stop the service if this is an upgrade. You should only be doing things that don't effect a running service at this point. Or if you're supper worried about that, you can stop it, do your work, and then start it again.

File: earth_enterprise/rpms/opengee-server/pre-uninstall.sh (hunk 17 above)
Comment (tst-dsugar) [reply earth_enterprise/rpms/opengee-server/pre-uninstall.sh]: You do have to stop it if it is an upgrade, because you are replacing the current executables with new ones. Well, you could do condrestart, but I wasnt sure if the current scripts supported that.
