### PR TITLE
Fixes #1105:  turn world-writable files back into symlinks

### LINKED ISSUE #1105: Files incorrectly world writable instead of links
To reproduce:
Build and install RPMs. Then `sudo find /opt/google/ -type f -exec ls -l {} \; | grep rwxrwxrwx`

Sample output:
```
-rwxrwxrwx. 1 root root 58192 Mar 31 09:37 /opt/google/bin/khinfo
-rwxrwxrwx. 1 root root 69400 Mar 31 09:41 /opt/google/bin/khmodifyvectorasset
-rwxrwxrwx. 1 root root 13824 Mar 31 09:41 /opt/google/bin/khbuild
-rwxrwxrwx. 1 root root 16344 Mar 31 09:41 /opt/google/bin/khclearbad
-rwxrwxrwx. 1 root root 16344 Mar 31 09:41 /opt/google/bin/khcancel
-rwxrwxrwx. 1 root root 32120 Mar 31 09:41 /opt/google/bin/khaddtoimageryproject
-rwxrwxrwx. 1 root root 65504 Mar 31 09:41 /opt/google/bin/khquery
-rwxrwxrwx. 1 root root 69400 Mar 31 09:41 /opt/google/bin/khnewvectorasset
-rwxrwxrwx. 1 root root 110408 Mar 31 09:41 /opt/google/bin/khmaskgen
-rwxrwxrwx. 1 root root 66640 Mar 31 09:41 /opt/google/bin/khmodifyimageryasset
-rwxrwxrwx. 1 root root 32120 Mar 31 09:41 /opt/google/bin/khaddtoterrainproject
-rwxrwxrwx. 1 root root 66640 Mar 31 09:41 /opt/google/bin/khnewimageryasset
-rwxrwxrwx. 1 root root 32120 Mar 31 09:41 /opt/google/bin/khmodifyimageryproject
-rwxrwxrwx. 1 root root 16344 Mar 31 09:41 /opt/google/bin/khresume
-rwxrwxrwx. 1 root root 32120 Mar 31 09:41 /opt/google/bin/khmodifyterrainproject
-rwxrwxrwx. 1 root root 6452904 Mar 31 09:29 /opt/google/bin/postmaster
-rwxrwxrwx. 1 root root 28232 Mar 31 09:41 /opt/google/bin/khnewdatabase
-rwxrwxrwx. 1 root root 16344 Mar 31 09:41 /opt/google/bin/khclean
-rwxrwxrwx. 1 root root 23792 Mar 31 09:41 /opt/google/bin/khdropfromvectorproject
-rwxrwxrwx. 1 root root 28784 Mar 31 09:41 /opt/google/bin/khtop
-rwxrwxrwx. 1 root root 19688 Mar 31 09:41 /opt/google/bin/khdropfromimageryproject
-rwxrwxrwx. 1 root root 23824 Mar 31 09:41 /opt/google/bin/khaddtovectorproject
-rwxrwxrwx. 1 root root 32120 Mar 31 09:41 /opt/google/bin/khnewimageryproject
-rwxrwxrwx. 1 root root 16344 Mar 31 09:41 /opt/google/bin/khsetbad
-rwxrwxrwx. 1 root root 32120 Mar 31 09:41 /opt/google/bin/khnewterrainproject
-rwxrwxrwx. 1 root root 66640 Mar 31 09:41 /opt/google/bin/khmodifyterrainasset
-rwxrwxrwx. 1 root root 270712 Mar 31 09:20 /opt/google/bin/ldapadd
-rwxrwxrwx. 1 root root 23824 Mar 31 09:41 /opt/google/bin/khnewvectorproject
-rwxrwxrwx. 1 root root 23824 Mar 31 09:41 /opt/google/bin/khmodifyvectorproject
-rwxrwxrwx. 1 root root 20992 Mar 31 09:37 /opt/google/bin/khtranslate
-rwxrwxrwx. 1 root root 85608 Mar 31 09:37 /opt/google/bin/khvirtualraster
-rwxrwxrwx. 1 root root 28232 Mar 31 09:41 /opt/google/bin/khmodifydatabase
-rwxrwxrwx. 1 root root 19688 Mar 31 09:41 /opt/google/bin/khdropfromterrainproject
-rwxrwxrwx. 1 root root 21040 Mar 31 09:37 /opt/google/bin/khreproject
-rwxrwxrwx. 1 root root 66640 Mar 31 09:41 /opt/google/bin/khnewterrainasset
-rwxrwxrwx. 1 root root 8690005 Apr 8 21:27 /opt/google/qt/lib/libqt-mt.so.3
-rwxrwxrwx. 1 root root 226576 Mar 31 09:25 /opt/google/qt/lib/libqui.so
-rwxrwxrwx. 1 root root 226576 Mar 31 09:25 /opt/google/qt/lib/libqui.so.1.0
-rwxrwxrwx. 1 root root 226576 Mar 31 09:25 /opt/google/qt/lib/libqui.so.1
-rwxrwxrwx. 1 root root 8690000 Apr 8 21:27 /opt/google/qt/lib/libqt-mt.so.3.3
-rwxrwxrwx. 1 root root 8690000 Mar 31 09:25 /opt/google/qt/lib/libqt-mt.so
-rwxrwxrwx. 1 root root 455960 Mar 31 09:19 /opt/google/lib/libssl.so
-rwxrwxrwx. 1 root root 352792 Mar 31 09:25 /opt/google/lib/libopenjp2.so.7
-rwxrwxrwx. 1 root root 352792 Mar 31 09:25 /opt/google/lib/libopenjp2.so
-rwxrwxrwx. 1 root root 77432 Mar 31 09:29 /opt/google/lib/libecpg.so
-rwxrwxrwx. 1 root root 48712 Mar 31 09:20 /opt/google/lib/liblber.so
-rwxrwxrwx. 1 root root 66400 Mar 31 09:29 /opt/google/lib/libpgtypes.so.3
-rwxrwxrwx. 1 root root 18208 Mar 31 09:29 /opt/google/lib/libecpg_compat.so
-rwxrwxrwx. 1 root root 184800 Mar 21 09:40 /opt/google/lib/libpq.so
-rwxrwxrwx. 1 root root 66400 Mar 31 09:29 /opt/google/lib/libpgtypes.so
-rwxrwxrwx. 1 root root 441064 Mar 31 09:21 /opt/google/lib/libcurl.so.4
-rwxrwxrwx. 1 root root 2304760 Mar 31 09:19 /opt/google/lib/libcrypto.so
-rwxrwxrwx. 1 root root 14957984 Mar 31 09:28 /opt/google/lib/libgdal.so.2
-rwxrwxrwx. 1 root root 48712 Mar 31 09:20 /opt/google/lib/liblber-2.4.so.2
-rwxrwxrwx. 1 root root 14957984 Mar 31 09:28 /opt/google/lib/libgdal.so
-rwxrwxrwx. 1 root root 242328 Mar 31 09:20 /opt/google/lib/libldap-2.4.so.2
-rwxrwxrwx. 1 root root 77432 Mar 31 09:29 /opt/google/lib/libecpg.so.6
-rwxrwxrwx. 1 root root 242328 Mar 31 09:20 /opt/google/lib/libldap.so
-rwxrwxrwx. 1 root root 263480 Mar 31 09:20 /opt/google/lib/libldap_r-2.4.so.2
-rwxrwxrwx. 1 root root 18208 Mar 31 09:29 /opt/google/lib/libecpg_compat.so.3
-rwxrwxrwx. 1 root root 263480 Mar 31 09:20 /opt/google/lib/libldap_r.so
-rwxrwxrwx. 1 root root 441064 Mar 31 09:21 /opt/google/lib/libcurl.so
-rwxrwxrwx. 1 root root 184800 Mar 21 09:40 /opt/google/lib/libpq.so.5
-rwxrwxrwx. 1 root root 67548 Mar 31 09:16 /opt/google/share/fonts/sans.ttf
```

The listed files should all be soft-links, but due to problems building the RPMs, they are actually files that are world writable (!!!).

The files listed here are on rhel 6 (but probably applies to all platforms).

### PR DESCRIPTION
**Pull request by tst-cjeffries**
Fixes #1105 

Turn world writable files back into symlinks in the rpm post-install script. Gradle resolves symlinks instead of preserving them, generating world-writable files instead of symlinks. This resolves this issue until the issue has been fixed in gradle or an alternative solution is found. This affects all platforms, so it must be tested on all of them (Centos 6/7, RHEL 6/7, Ubuntu 14/16).

To test:

1. Build OpenGEE RPMs. See the build [instructions](https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD.md). The following command does all the building:
`scons -j8 release=1 build; scons -j8 release=1 stage_install; scons -j8 release=1 package_install`

2. Install those RPMs using yum (or dpkg on Ubuntu).

3. `sudo find /opt/google/ -type f -exec ls -l {} \; | grep rwxrwxrwx`

4. Verify there is no output.

### CODE REVIEW

File: earth_enterprise/rpms/opengee-fusion/snippets/post-install.sh [hunk 1]
```diff
@@ -67,6 +69,97 @@ main_postinstall()
 # Post-install Functions
 #-----------------------------------------------------------------
 
+fix_symlinks()
```
Comment (tst-ppenev) [inline earth_enterprise/rpms/opengee-fusion/snippets/post-install.sh]: Please, fix symlinks in the Gradle file instead of doing this.  This is not as clean, as not secure.

Look at the `link` commands in the `openGeeServerRpm` task for examples of packaging symlinks.

Comment (tst-ppenev) [reply earth_enterprise/rpms/opengee-fusion/snippets/post-install.sh]: A better way to fix it is to add an option to the `GeeRpm` and `GeeDeb` classes to scan for symlinks in a package, and add them as symlinks before packaging.

Listing them manually is OK for a hot fix.  However, it will be prone to getting out of date and creating security issues anytime this list of symlinks changes, and a corresponding update isn't made in the Gradle scripts.

Comment (tst-cjeffries) [reply earth_enterprise/rpms/opengee-fusion/snippets/post-install.sh]: Right. I am going to look into it. The reason this ticket came up is due to Gradle handling the links incorrectly.

Comment (tst-cjeffries) [reply earth_enterprise/rpms/opengee-fusion/snippets/post-install.sh]: Looks like I will be able to do it this way. Will take a little bit to implement everything in Gradle, but it looks doable.

Comment (tst-ppenev) [reply earth_enterprise/rpms/opengee-fusion/snippets/post-install.sh]: Great.

Also, I may be able to give some answers, if Gradle questions come up.

Comment (tst-cjeffries) [reply earth_enterprise/rpms/opengee-fusion/snippets/post-install.sh]: Have made adjustments so symlinks are fixed in Gradle instead of the post install script.

File: earth_enterprise/rpms/buildSrc/src/main/groovy/GeeDeb.groovy [hunk 2]
```diff
@@ -134,6 +136,10 @@ class GeeDeb extends com.netflix.gradle.plugins.deb.Deb {
         packageDescription = formattedDescription
     }
 
+    // Variable to autodetect symlinks. Detected symlinks are fixed, so they
+    // are not created as files.
+    boolean autoSymlinkDetection = true
```
Comment (tst-ppenev) [inline earth_enterprise/rpms/buildSrc/src/main/groovy/GeeDeb.groovy]: Minor: I think `autoSymlinkDetection` is not very informative of the effect you get when you set it to `true`.  I think a better name may be something like `preserveSymlinks`.

File: earth_enterprise/rpms/buildSrc/src/main/groovy/GeeDeb.groovy [hunk 3]
```diff
@@ -153,7 +159,16 @@ class GeeDeb extends com.netflix.gradle.plugins.deb.Deb {
             each {
                 requires(it)
             }
-
+        
+        if (autoSymLinkDetection) {
+            eachFile {
+                if (it.getFile().isFile() && Files.isSymbolicLink(it.getFile().toPath())) {
+                    link("/" + it.getRelativePath().toString(), Files.readSymbolicLink(it.getFile().toPath()).toString())
```
Comment (tst-ppenev) [inline earth_enterprise/rpms/buildSrc/src/main/groovy/GeeDeb.groovy]: I realize I may have suggested rewriting symlinks, but looking at here, I don't I'd want the symlink targets rewritten behind my back, at least, not without an explicit request for it.

I think, if this is to be fixed, it should be done in the `khEnvironment.installedExecutableSymlink` method.  That may be outside the scope of this ticket, so it may best to leave the link targets unmodified here.

File: earth_enterprise/rpms/buildSrc/src/main/groovy/GeeDeb.groovy (hunk 2 above)
Comment (tst-cjeffries) [reply earth_enterprise/rpms/buildSrc/src/main/groovy/GeeDeb.groovy]: Changed.

File: earth_enterprise/rpms/buildSrc/src/main/groovy/GeeDeb.groovy (hunk 3 above)
Comment (tst-cjeffries) [reply earth_enterprise/rpms/buildSrc/src/main/groovy/GeeDeb.groovy]: I was under the impression that the issue was that symlinks did not survive the copy operation done by Gradle. How would we go about fixing that issue in/with `khEnvironment.installedExecutableSymlink`?

**Comment by tst-cjeffries** [comment]
Release notes have been updated.

**Comment by tst-cjeffries** [comment]
@tst-ccamp Does this still need to target 5.2.5? If so how do I adjust that?

File: earth_enterprise/rpms/buildSrc/src/main/groovy/GeeDeb.groovy (hunk 3 above)
Comment (tst-ppenev) [reply earth_enterprise/rpms/buildSrc/src/main/groovy/GeeDeb.groovy]: You're right.

I wasn't paying enough attention when reading this code.  It looks fine.

**Comment by tst-dsugar** [comment]
This tested okay
