### PR TITLE
Fixes #1037: Add new CLI parameter to match UI levels.

### LINKED ISSUE #1037: Projects use different level numbers on CLI than displayed in Fusion UI
Originally this was thought to only affect Terrain, but I've confirmed that it also effect Imagery Project CLI, but the level number is off by a different amount. Although unconfirmed, this may affect vector, but that interface is different from the other two. Affected CLI utilities are `genew*project`, `gemodify*project`, `geaddto*project`

## Reproduction steps
1. Create a terrain resource and note its maximum level 
** You can do this by temporarily adding it to a terrain project using the Fusion UI, then remove it afterward
1. Use `genewterrainresource` (or `gemodifyterrainresource`) to add your new resource and specify maximum level of 1 less than the maximum shown in step 1
    ```
    $  /opt/google/bin/genewterrainproject -o Projects/MyTerrainProject --maxlevel 29 Resources/Terrain/MyTerrainResource
    ```
1. Open Asset Manager in Fusion UI
1. Open the new terrain project that was created
1. Look at the override level indicated in the Terrain Project window (You may have to expand the window to see all of the text)

**Expected**: The terrain shown in the Terrain Project window displays the same override level than the one specified on the CLI

**Actual**: The terrain shown in the Terrain Project window displays an override level that is 5 levels lower than the one specified on the CLI

image

Similar reproduction steps can be used for imagery import.

### PR DESCRIPTION
**Pull request by tst-cjeffries**
Fixes issue #1037. Adds a new CLI parameter, `--maxleveloverride`, for `genew*project`, `geaddto*project`, and `gemodify*project`. This parameter does the same thing as `--maxlevel` but uses the Terrain/Imagery levels instead of the internal "Product" level so that it matches the Fusion UI. At the same time, we will deprecated `--maxlevel`.

To test, install OpenGEE (Id recommend a clean VM) and add some imagery/terrain using the CLI and the `--maxleveloverride` parameter. The following commands can  be run as a shell script, or manually.

```
cd ~

git clone https://github.com/tst-cjeffries/earthenterprise.git

cd earthenterprise/earth_enterprise

sudo /etc/init.d/gefusion stop
sudo /etc/init.d/geserver stop

sudo ./src/installer/uninstall_fusion.sh
sudo ./src/installer/uninstall_server.sh

sudo rm -r /gevol

scons -j8 release=1 build
scons -j8 release=1 stage_install

sudo ./src/installer/install_server.sh
sudo ./src/installer/install_fusion.sh

sudo /etc/init.d/geserver stop
sudo /etc/init.d/geserver start

sudo /etc/init.d/gefusion stop
sudo /etc/init.d/gefusion start

cd /opt/google/share/tutorials/fusion
sudo ./download_tutorial.sh

cd ~

export PATH=$PATH:/opt/google/bin

genewimageryresource -o TestImageryResourceNew /opt/google/share/tutorials/fusion/Imagery/i3SF15-meter.tif
genewimageryresource -o TestImageryResourceDeprecated /opt/google/share/tutorials/fusion/Imagery/i3SF15-meter.tif
genewterrainresource -o TestTerrainResourceNew /opt/google/share/tutorials/fusion/Terrain/SF_terrain.tif
genewterrainresource -o TestTerrainResourceDeprecated /opt/google/share/tutorials/fusion/Terrain/SF_terrain.tif

genewimageryproject -o TestImageryProject
geaddtoimageryproject -o TestImageryProject --maxlevel 12 TestImageryResourceDeprecated
geaddtoimageryproject -o TestImageryProject --maxleveloverride 12 TestImageryResourceNew
genewterrainproject -o TestTerrainProject
geaddtoterrainproject -o TestTerrainProject --maxlevel 10 TestTerrainResourceDeprecated
geaddtoterrainproject -o TestTerrainProject --maxleveloverride 10 TestTerrainResourceNew
genewimageryproject -o TestImageryProject2 --maxleveloverride 12 TestImageryResourceNew
genewimageryproject -o TestImageryProject3 --maxleveloverride 12 TestImageryResourceNew
gemodifyimageryproject -o TestImageryProject3 --maxleveloverride 11 TestImageryResourceNew
genewterrainproject -o TestTerrainProject2 --maxleveloverride 10 TestTerrainResourceNew
genewterrainproject -o TestTerrainProject3 --maxleveloverride 10 TestTerrainResourceNew
gemodifyterrainproject -o TestTerrainProject3 --maxleveloverride 9 TestTerrainResourceNew
```

After running these commands, the first two imagery/terrain projects should have two resources, one for the new and one for the old maxlevel commands. The new command resource should have the FusionUI level matching the level provided in the parameter. The deprecated command resource should not match, and should be 8 levels lower for imagery, and 5 levels lower for terrain. Terrain/ImageryProject2 should have a single resource that matches the CLI parameter, and Terrain/ImageryProject3 should have a single resource that matches the CLI parameter of the modify command.

### CODE REVIEW

File: earth_enterprise/src/fusion/autoingest/tools/geaddtoimageryproject.cpp [hunk 1]
```diff
@@ -105,6 +109,24 @@ main(int argc, char *argv[]) {
...
+      if (AssetType == AssetDefs::Imagery) {
+        overridemax = ImageryToProductLevel(overridemax);
+      }
+      else {
+        overridemax = TmeshToProductLevel(overridemax);
+      }
+    }
+    
+    if (overridemax_deprecated) {
+      overridemax = overridemax_deprecated;
```
Comment (tst-ccamp) [inline earth_enterprise/src/fusion/autoingest/tools/geaddtoimageryproject.cpp]: I suggest that we output a message here letting the user know that the command is deprecated and suggest the other one instead.

File: docs/geedocs/5.2.5/answer/3481558.html [hunk 2]
```diff
@@ -89,8 +89,15 @@ <h3>Commands</h3>
   <pre>
 <code><b>--no_historical_imagery </b></code></pre>
   <p><i>Default</i>. Uses normal imagery for the project.</p>
-  <h2><a name="63542"></a>geconfigureassetroot</h2>
+  <h3>Options</h3>
+  <pre>
+  <code><b>--maxlevel </b><i>level</i></code></pre>
+  <div class="alert"> Deprecated in release GEE 5.2.5 and higher. Use <code>--maxleveloverride</code></a> instead.</div>
+  <p><i>Optional</i>. Sets the maximum level for the imagery. Uses internal Fusion scale. Does not match the levels in the Fusion UI.</p>
```
Comment (tst-ccamp) [inline docs/geedocs/5.2.5/answer/3481558.html]:
```suggestion
  <p><i>Optional</i>. Sets the maximum level for the imagery. Uses internal Fusion scale. Deprecated because it not match the levels specified in the Fusion UI.</p>
```

File: docs/geedocs/5.2.5/answer/3481558.html [hunk 3]
```diff
@@ -89,8 +89,15 @@ <h3>Commands</h3>
...
   <pre>
+  <code><b>-maxleveloverride </b><i>level</i></code></pre>
```
Comment (tst-ccamp) [inline docs/geedocs/5.2.5/answer/3481558.html]:
```suggestion
  <code><b>--maxleveloverride </b><i>level</i></code></pre>
```

Needs the double dash

File: docs/geedocs/5.2.5/answer/3481558.html (hunk 2 above)
Comment (tst-cjeffries) [reply docs/geedocs/5.2.5/answer/3481558.html]: So those other CLI utilities are all compiled from this one .cpp file.

Comment (tst-cjeffries) [reply docs/geedocs/5.2.5/answer/3481558.html]: Also worth noting: that aside from the geaddtoimageryproject, those other CLI utilities do not have any documentation. So if you want those documented, they will need entire documentation written. Also the help text is only for geaddtoimageryproject (though it is (mostly) applicable to the others.

**Comment by tst-ccamp** [comment]
I signed the CLA and consent to allow my changes

File: earth_enterprise/src/fusion/autoingest/tools/geaddtoimageryproject.cpp (hunk 1 above)
Comment (tst-cjeffries) [reply earth_enterprise/src/fusion/autoingest/tools/geaddtoimageryproject.cpp]: Added a deprecated message.

**Comment by tst-ccamp** [comment]
I was able to verify that the utilities do accept the new parameter, but the help output for the commands do not display the new parameter. I think the code that was update only effects the parser, not the help output. 
```
usage: geaddtoimageryproject [options] -o <projectname> {[--maxlevel <level>] <insetresource>}...
   Supported options are:
      --help | -?:      Display this usage message
      --mercator : use mercator projection
      --flat : use flat(Plate Carre) projection (default)
      --historical_imagery : change this project to be a historical
                             imagery project
      --no_historical_imagery : make this a normal project
                         (i.e., not a historical imagery project)
   By default, new projects are NOT time machine projects unless --historical_imagery is specified.
```
